book/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book_app.urls')),
    path('accounts/', include('allauth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book_app/urls.py
from django.urls import path
from book_app.views import delete_from_cart
from book_app import views

urlpatterns = [
    path('', views.home, name='home'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('loginpage/', views.loginpage, name='loginpage'),
    path('logoutpage/', views.logoutpage, name='logoutpage'),
    path('sell/',views.sell, name="sell"),
    path('sellformcreated/',views.sellformcreated, name="sellformcreated"),
    path('borrow/', views.borrow, name='borrow'),
    path('all_sell_items/',views.all_sell_items, name="all_sell_items"),
    path('book_detail/<uuid>', views.book_detail, name='book_detail'),
    path('all_cart_items/', views.all_cart_items, name='all_cart_items'),
    path('add_to_cart/<uuid>', views.add_to_cart, name='add_to_cart'),
    path('cart/<pk>/delete', delete_from_cart.as_view(), name='delete_from_cart'),
    path('search/', views.search, name='search'),
]

book_app/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
# Create your models here.

class custom_user(models.Model):
    userlink=models.OneToOneField(User, on_delete=models.CASCADE)
    firstname=models.CharField('Firstname',max_length=30)
    lastname=models.CharField('Lastname',max_length=30)
    phone=models.CharField('Phone No.',max_length=15,unique=True)
    email=models.EmailField('Email',max_length=100,unique=True)
    username=models.CharField('Username',max_length=30, unique=True)
    user_pin=models.CharField('Pincode', max_length=6, validators=[MinLengthValidator(6)])

    def __str__(self):
        return self.firstname+" "+self.lastname

class Sell(models.Model):
    # CHANGE
    owner=models.ForeignKey(User, on_delete=models.CASCADE)
    book_name=models.CharField('Book Name',max_length=200, help_text="Enter the book name")
    author=models.CharField('Author',max_length=200, help_text="Enter the book's author name")
    published_by=models.CharField('Published By',max_length=200)
    FIRSTHAND='Firsthand'
    SECONDHAND='Secondhand'
    TYPE_CHOICES=[
        ('Firsthand','Firsthand'),
        ('Secondhand','Secondhand'),
    ]
    TAG_CHOICES=[
        ('ACTION','Action'),
        ('THRILLER','Thriller'),
        ('ART','Art'),
        ('ROMANCE','Romance'),
        ('FAIRYTALE','Fairytale'),
        ('TRUE CRIME','True_crime'),
        ('DRAMA','Drama'),
        ('DIARY','Diary'),
        ('COMIC','Comic'),
        ('HISTORY','History'),
        ('HORROR','Horror')
    ]
    DIS_CHOICES=[
        ('40%','40%'),
        ('50%','50%'),
        ('60%','60%'),
        ('70%','70%'),
        ('80%','80%'),
        ('90%','90%'),
        ('100%','100%')
    ]
    tags=models.CharField('Tag',max_length=20, choices=TAG_CHOICES)
    types=models.CharField('Type',max_length=30, choices=TYPE_CHOICES, default=SECONDHAND)
    price=models.DecimalField('Price',max_digits=10, decimal_places=2, help_text="Enter the book's price")
    discount=models.CharField('Discount',max_length=20, choices=DIS_CHOICES, default='40%')
    pin_code=models.CharField('Pincode', max_length=6, validators=[MinLengthValidator(6)], help_text="Enter the pincode of your suitable area to sell")
    description=models.TextField('Description',max_length=300, help_text="Please add if any extra info is there for the book", null=True)
    photo = models.ImageField('Photo Of Book',upload_to='photos/',blank=True,null=True)

    def __str__(self):
        return self.book_name+"-"+self.author

class Cart(models.Model):
    seller=models.ForeignKey(Sell, on_delete=models.CASCADE)

book_app/forms.py
from django import forms
from django.contrib.auth.models import User
from book_app.models import custom_user, Sell

class UserForm(forms.ModelForm):
    password = forms.CharField(max_length=32, widget=forms.PasswordInput)
    class Meta:
        model = custom_user
        fields = ['firstname','lastname','username','email','user_pin','phone','password']

class SellForm(forms.ModelForm):
    class Meta:
        model=Sell
        fields=['book_name','author','published_by','tags','types','discount','price','pin_code','description','photo']

book_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth import login, authenticate, logout
from django.views.generic.edit import CreateView, DeleteView
from book_app.forms import UserForm, SellForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required 
import decimal
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from .models import Sell, Cart, custom_user
from . import views

# Create your views here.

def home(request):
    return render(request,'home.html')

def sign_up(request):
    if request.method=='POST':
        form=UserForm(request.POST or None)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = User.objects.create_user(username=username,email=email,password=password)
            user.save()
            obj=form.save(commit=False)
            obj.userlink_id=user.id
            obj.save()
            login(request, user)
            return redirect("home")
    form = UserForm()
    return render(request, 'sign_up.html', {'form': form})


def loginpage(request):
    form = AuthenticationForm(request.POST)
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=authenticate(username=username,password=password)
        if user is not None:
            login(request, user)
            return render(request,'home.html')
    return render(request,'login.html',{'form':form})

@login_required
def logoutpage(request):
    logout(request)
    return redirect("home")

@login_required
def sellformcreated(request):
    return render(request,'sellformcreated.html')

@login_required
def sell(request):
    if request.method == 'POST':
        form = SellForm(request.POST, request.FILES)
        if form.is_valid():
            ans = form.save(commit = False)
            ans.owner = request.user
            ans.save()
            return redirect("all_sell_items")
    return render(request,'sellform.html',{'form': SellForm()})

@login_required
def borrow(request):
    curr_user=custom_user.objects.get(userlink=request.user)
    books=Sell.objects.filter(pin_code=curr_user.user_pin).exclude(owner=request.user)
    return render(request,'borrow.html',{'books':books})

@login_required
def all_sell_items(request):
    books=Sell.objects.filter(owner=request.user)
    cnt=Sell.objects.filter(owner=request.user).count()
    return render(request,'sellformcreated.html',{'books':books,'count':cnt})

@login_required
def book_detail(request, uuid):
    book=Sell.objects.filter(pk=uuid)
    original_price=Sell.objects.get(id=uuid).price
    discount_price=Sell.objects.get(id=uuid).discount
    if discount_price=="40%":
        x=40
    elif discount_price=="50%":
        x=50
    elif discount_price=="60%":
        x=60
    elif discount_price=="70%":
        x=70
    elif discount_price=="80%":
        x=80
    elif discount_price=="90%":
        x=90
    else:
        x=100
    x=decimal.Decimal(x)*decimal.Decimal(original_price)*decimal.Decimal(0.01)
    x=round(x,2)
    x=decimal.Decimal(original_price)-x
    return render(request,'book_detail.html',{'books':book,'original':original_price,'selling':x})

@login_required
def all_cart_items(request):
    cart_items=Cart.objects.all()
    cnt=Cart.objects.all().count()
    print(cart_items)
    return render(request,"all_cart_items.html",{'cart_items':cart_items,'count':cnt})

@login_required
def add_to_cart(request,uuid):
    cnt=Cart.objects.filter(seller_id=uuid).count()
    if cnt:
        pass
    else:
        cart_item=get_object_or_404(Sell, pk=uuid)
        obj=Cart(seller=cart_item)
        obj.save()
    cart_items=Cart.objects.all()
    cnt=Cart.objects.all().count()
    return render(request,"add_to_cart.html",{'cart_items':cart_items,'count':cnt})


class delete_from_cart(DeleteView):
    model=Cart
    success_url=reverse_lazy("all_cart_items")

@login_required
def search(request):
    input_q=request.GET.get("search_title")
    searched_items=Sell.objects.filter(book_name__icontains=input_q)
    return render(request,'borrow.html',{'books':searched_items}) 

book_app/templates/add_to_cart.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static '/css/add_to_cart.css' %}">

<section>
  <div class="row">
    <div class="col-lg-8">
      <div class="card wish-list mb-3">
        <div class="card-body">
          <h1 style="margin-bottom:40px;color:black;"><u>Your cart items include</u></h1>
          <h5 class="mb-4">Cart (<span>{{count}}</span> items)</h5>
    	    {% for item in cart_items %}
          <div class="row mb-4">
            <div class="col-md-5 col-lg-3 col-xl-3">
              <div class="view zoom overlay z-depth-1 rounded mb-3 mb-md-0">
                <img class="img-fluid w-100" src="{{item.seller.photo.url}}" alt="Sample">
              </div>
            </div>
            <div class="col-md-7 col-lg-9 col-xl-9">
              <div>
                <div class="d-flex justify-content-between">
                  <div>
                    <p class="mb-3 text-muted text-uppercase small"><b>Book Name - {{item.seller.book_name}}</b></p>
                    <p class="mb-2 text-muted text-uppercase small">Author Name - {{item.seller.author}}</p>
                    <p class="mb-3 text-muted text-uppercase small">Published By - {{item.seller.published_by}}</p>
		                <p class="mb-3 text-muted text-uppercase small">Book Type : {{item.seller.types}}</p>
                    <p class="mb-0"><span><strong>Original Price - {{item.seller.price}}</strong></span></p>
                    <p>
                      <form action="{% url 'delete_from_cart' item.id %}" method="post"  style="display: inline;">
                        {% csrf_token %}
                            <button type="submit" class="btn btn-warning" style="margin-top: -18px">REMOVE FROM CART</button>
                      </form>		  
                      <a href="#" class="btn btn-info"> PURCHASE THE BOOK </a>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <hr class="mb-4">
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>


{% endblock %}

book_app/templates/all_cart_items.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static '/css/borrow.css' %}">

  <div id="wrapper">
  
    <!-- Sidebar -->
    <div id="sidebar-wrapper">
      <ul class="sidebar-nav" style="color: white;">
        <li>
          <a href="#">Price</a>
        </li>
        <li>
          <a href="#">Tag</a>
        </li>
        <li>
          <a href="#">Type</a>
        </li>
      </ul>
    </div>
  
    <!-- Page Content -->
    <div id="page-content-wrapper">
      <div class="container-fluid">
        <a href="#menu-toggle" class="btn btn-secondary float-right" id="menu-toggle">Filter Here-></a>
        <h1 style="margin-bottom:40px;color:white;"><u>Search and explore your books</u></h1>
  
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
        {% if count %}
        {% for item in cart_items %}
          <div class="col mb-4">
            <div class="card h-100" style="filter: drop-shadow(13px 13px 13px #9c9a9a); border-radius:25px; background-color:black; border: 1px solid white; color:white;">
              <img src="{{ item.seller.photo.url }}" class="card-img-top" style="height: 10rem; border-radius:25px;" alt="{{item.book_name}}">
              <div class="card-body">
                <p class="card-title"><b>Book Name :</b> {{item.seller.book_name}}</p>
                <p class="card-text"><b>Author :</b> {{item.seller.author}}</p>
                <p class="card-text"><b>Published By :</b> {{item.seller.published_by}}</p>
                <a class="btn btn-warning" style="float:right;" href="{% url 'book_detail' item.seller.id %}">View book-></a>
              </div>
            </div>
          </div>
        {% endfor %}
        {% else %}
          <div class="container">
            <div class="container">
              <div class="jumbotron">
                <h3>There are zero items in your cart.</h3>
              </div>
            </div>
          </div>
        {% endif %}
        
      </div>

    </div>
  </div>

</div>



<!-- CART_ITEMS.JS -->


<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta.3/js/bootstrap.js'></script>
<script src="{% static '/js/borrow.js' %}"></script>

{% endblock %}

book_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>BOOK APP</title>
    <!-- BOOTSTRAP CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- CSS OF BASE.HTML -->
    <link rel="stylesheet" href="{% static '/css/base.css' %}">
    <!-- FONT FAMILY -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Cairo&display=swap" rel="stylesheet">
  </head>
  <body style="font-family: 'Cairo', sans-serif;">


    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link disabled" href="#">WELCOME : {{user}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "sell" %}">Sell</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "borrow" %}">Borrow</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "all_sell_items" %}">MyBooks</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "all_cart_items" %}">MyCart</a>
                </li>
                {% else %}
                <li class="nav-item active">
                    <a class="nav-link disabled" href="#">WELCOME</a>
                </li>
                {% endif %}
            </ul>
        </div>
        <div class="mx-auto order-0">
            {% if user.is_authenticated %}
            <a class="navbar-brand mx-auto disabled" href="{% url "home" %}">LIBOOK</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
                <span class="navbar-toggler-icon"></span>
            </button>
            {% endif %}
        </div>
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
            <ul class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
              <form class="form-inline my-2 my-lg-0" action="{% url 'search' %}" method="GET">
                  <input class="form-control mr-sm-2" type="search" name="search_title" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>
              <li class="nav-item">
                  <a class="nav-link" href="{% url "logoutpage" %}">Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url "sign_up" %}">SignUp</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url "loginpage" %}">Login</a>
              </li>
              {% endif %}
            </ul>
        </div>
    </nav>

   {% block content %}
   {% endblock %}

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

  </body>

</html>

book_app/templates/book_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static '/css/book_detail.css' %}">
<link rel="stylesheet" href="https://awik.io/demo/webshop-zoom/drift-basic.min.css">

{% for book in books %}
<div id="col-1">
  <img class="drift-demo-trigger" data-zoom="{{book.photo.url}}" src="{{book.photo.url}}"><br>
  <caption>( Cursor over image for a clearer view )</caption>
</div>
<div id="col-2">
  <div id="left">
    <h2><u>{{ book.book_name }}</u></h2>
    <p><b>Description : </b>{{ book.description }}</p>
    <p><b><u>SPECIFICATIONS :-</u></b></p>
    <p><b>Author Name :</b> {{book.author}}</p>
    <p><b>Published By :</b> {{book.published_by}}</p>
    <p><b>Book Type :</b> {{book.types}}</p>
    <p><b>Book genre/tag :</b> {{book.tags}}</p>
    <p><b>Original Price :</b> {{original}}</p>
    <p><b>Selling Price :</b> {{selling}}</p>
    <a href="{% url 'add_to_cart' book.id %}" class="btn btn-info"> ADD TO CART </a>
    <a href="#" class="btn btn-info"> PURCHASE THE BOOK </a>
  </div>
  <div id="right">
    <div id="details-container">
    </div>
  </div>
</div>



{% endfor %}

<script src="https://awik.io/demo/webshop-zoom/Drift.min.js"></script>
<script src="{% static '/js/book_detail.js' %}"></script>

{% endblock %}

book_app/templates/borrow.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static '/css/borrow.css' %}">

<div id="wrapper">

  <!-- Sidebar -->
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav" style="color: white;">
      <li>
        <a href="#">Price</a>
      </li>
      <li>
        <a href="#">Tag</a>
      </li>
      <li>
        <a href="#">Type</a>
      </li>
    </ul>
  </div>






  <!-- Page Content -->
  <div id="page-content-wrapper">
    <div class="container-fluid">
      <a href="#menu-toggle" class="btn btn-secondary float-right" id="menu-toggle">Filter Here-></a>
      <h1 style="margin-bottom:40px;color:white;"><u>Search and explore your books</u></h1>

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
        {% for book in books %}
          <div class="col mb-4">
            <div class="card h-100" style="filter: drop-shadow(13px 13px 13px #9c9a9a); border-radius:25px; background-color:black; border: 1px solid white; color:white;">
              <img src="{{ book.photo.url }}" class="card-img-top" style="height: 10rem; border-radius:25px;" alt="{{book.book_name}}">
              <div class="card-body">
                <p class="card-title"><b>Book Name :</b> {{book.book_name}}</p>
                <p class="card-text"><b>Author :</b> {{book.author}}</p>
                <p class="card-text"><b>Published By :</b> {{book.published_by}}</p>
                <a class="btn btn-warning" style="float:right;" href="{% url 'book_detail' book.id %}">View book-></a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>

    </div>
  </div>

</div>



<!-- BORROW.JS -->


<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta.3/js/bootstrap.js'></script>
<script src="{% static '/js/borrow.js' %}"></script>

{% endblock %}

book_app/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}Sucess{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static '/css/home.css' %}">
<div class="first">
  <img src="{% static '/pics/first_logo.jpg' %}" alt="awwwwsnap" style="width:100%;height:500px;">
  <div class="centered"><h1>Lets Change The World Into A Library</h1></div>
</div>

<!-- SECOND -->

<div class="container">
  <h1>What do we provide</h1>
  <div class="row">
    <div class="col">
      <img style="float: right;" src="{% static '/pics/lend_borrow.jpg' %}" alt="">
    </div>
    <div class="col" style="text-align:left">
      <h4>Books are unread until you it is shared with other readers</h4>
      <p>
        “A book lying idle on a shelf is wasted ammunition. Like money, books must be kept in constant circulation. Lend and borrow to the maximum.”<br>
        — Henry Miller<br>
        Get the nearest lender or borrower with just few clicks and communicate to him/her through our platform.Donot throw books share it and make dreams come true.
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col"  style="text-align:right">
      <h4>Buy a book at a much lower cost and effort</h4>
      <p>
        Yes, buy the book you want to explore at a much lower price without spending time in the market to bargain.Our site finds the nearest seller to you with a discounted price as per our policy.Spend money on books and help others in changing the world.That's the thing about books.They let you travel without moving your feet.
      </p>
    </div>
    <div class="col" style="text-align:center">
      <img src="{% static '/pics/buy_book.png' %}" alt="">
    </div>
  </div>
</div>

{% endblock %}

book_app/templates/login.html
{% extends "base.html" %}
{% load static %}
{% load socialaccount %}
{% providers_media_js %}
{% block title %}Home Page{% endblock %}
{% block content %}

<link rel="stylesheet" href="{% static '/css/login.css' %}">

<form method="post">
  {% csrf_token %}
  <div class="styling">
    <h1>Login Here!</h1>
    <p><label for="id_username">Username : </label> <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username"></p>
    <p><label for="id_password">Password :  </label> <input type="password" name="password" autocomplete="current-password" required="" id="id_password"></p>
    <button type="submit" class="btn btn-outline-warning">Login</button>
    <a class="btn btn-outline-warning" href="{% provider_login_url "google" %}">LOGIN USING GOOGLE</a>
    <caption><b>If not a user ? </b></caption><a href="{% url 'sign_up' %}">Register Here</a>
  </div>
</form>

{% endblock %}

book_app/templates/logout.html
<!-- {% extends "base.html" %}
{% block title %}Home Page{% endblock %}
{% block content %}

<h1>Do you want to logout of your account?</h1>
<a href="{% url "home" %}" class="btn btn-danger">Yes</a>
<a href="{% url "logout" %}" class="btn btn-danger">No</a>

{% endblock %} -->

book_app/templates/sellform.html
{% extends "base.html" %}
{% load static %}
{% block title %}Sell Form Page{% endblock %}
{% block content %}

<link rel="stylesheet" href="{% static '/css/sellform.css' %}">

<div class="container">
  <h1>Please Fill The Sellers Form!</h1>
  <form class="styling" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input id="in" class="btn btn-outline-warning" type="submit" value="Sell">
  </form>
</div>
{% endblock %}

book_app/templates/sellformcreated.html
{% extends "base.html" %}
{% block title %}Sucess{% endblock %}
{% load static %}
{% block content %}
<!-- <div class="container">
  <h1>Your book is now available for the users to buy :)</h1>
</div> -->


<section>
  <div class="row">
    <div class="col-lg-8">
      <div class="card wish-list mb-3">
        <div class="card-body">
          <h1 style="margin-bottom:40px;color:black;"><u>Your contributions</u></h1>
          <h5 class="mb-4">Total : (<span>{{count}}</span> items) shared</h5>
    	    {% for book in books %}
          <div class="row mb-4">
            <div class="col-md-5 col-lg-3 col-xl-3">
              <div class="view zoom overlay z-depth-1 rounded mb-3 mb-md-0">
                <img class="img-fluid w-100" style="border-radius: 10px;" src="{{book.photo.url}}" alt="Sample">
              </div>
            </div>
            <div class="col-md-7 col-lg-9 col-xl-9">
              <div>
                <div class="d-flex justify-content-between">
                  <div>
                    <p class="mb-3 text-muted text-uppercase small"><b>Book Name - {{book.book_name}}</b></p>
                    <p class="mb-2 text-muted text-uppercase small">Author Name - {{book.author}}</p>
                    <p class="mb-3 text-muted text-uppercase small">Published By - {{book.published_by}}</p>
		                <p class="mb-3 text-muted text-uppercase small">Book Type : {{book.types}}</p>
                    <p class="mb-0"><span><strong>Original Price - {{book.price}}</strong></span>
                      <a style="float:right;margin-left:30px;" href="{% url 'book_detail' book.id %}">View book for selling rate-></a>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <hr class="mb-4">
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>


{% endblock %}

book_app/templates/sign_up.html
{% extends "base.html" %}
{% load static %}
{% block title %}Signup Page{% endblock %}
{% block content %}

<link rel="stylesheet" href="{% static '/css/register.css' %}">

<div class="container">
  <h1>Register Here!</h1>
  <form class="styling" method="post">
    {% csrf_token %}
    <p><label for="id_firstname">Firstname : </label> <input type="text" name="firstname" maxlength="30" required="" id="id_firstname"></p>
    <p><label for="id_lastname">Lastname : </label> <input type="text" name="lastname" maxlength="30" required="" id="id_lastname"></p>
    <p><label for="id_username">Username : </label> <input type="text" name="username" maxlength="30" required="" id="id_username"></p>
    <p><label for="id_email">Email :  </label> <input type="email" name="email" maxlength="100" required="" id="id_email"></p>
    <p><label for="id_user_pin">Pincode :  </label> <input type="text" name="user_pin" maxlength="6" required="" id="id_user_pin"></p>
    <p><label for="id_phone">Phone : </label> <input type="text" name="phone" maxlength="15" required="" id="id_phone"></p>
    <p><label for="id_password">Password : </label> <input type="password" name="password" maxlength="32" required="" id="id_password"></p>
    <input id="in" class="btn btn-outline-warning" type="submit" value="SignUp">
    <caption><b> Do you already have an account? </b></caption><a href="{% url 'loginpage' %}">Login Here</a>
  </form>
</div>
{% endblock %}